kind: api
apiVersion: api.webmethods.io/v1
metadata:
  name: DasoAPI
  namespace: dev
  version: 1.0
  tags:
    - swagger
    - daso
    - sample
  type: REST
spec:
  api-spec: 
    $path: petstore.yaml
  policy-seq: 
    - $ref: dev:dev_policies:1.0