kind: IdentifyAndAuthorize
apiVersion: api.webmethods.io/beta
metadata:
  name: IdentifyAndAuthorize
  namespace: dev
  version: '1.0'
  tags: []
spec:
  identificationType:
    and:
      apiKey:
        applicationLookup: registered
      hostNameAddress:
        applicationLookup: registered
      httpBasicAuth:
        applicationLookup: global
      openIdConnect:
        applicationLookup: registered
      sslCertificate:
        applicationLookup: default
  triggerPolicyViolation: false
